version: '2.1'

services:
  php:
    build: .
    ports:
    - "8020:80"
    volumes:
    - ./src:/var/www/html
    depends_on: 
    - db

  db:
    ports:
    - "3306:3306"
    image: mysql:5.7
    volumes:
    - ./db:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=123456
    - MYSQL_DATABASE=outside